### ISSUE TITLE
Libraries file seems to be outdated

### ISSUE THREAD

**Issue by androideveloper** [mikepenz/AboutLibraries#188]
This files seems to be outdated 
https://github.com/mikepenz/AboutLibraries/wiki/Compatible-Libs

I use ckchangelog, but it can't find the library.

**Comment by androideveloper** [comment]
How to include MaterialDrawer without autodetect?

**Comment by mikepenz** [comment]
@androideveloper the MaterialDrawer has the definition file included within the lib:
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/res/values/library_materialdrawer_strings.xml
The key is `materialdrawer` 

As far as I see there is no ckchangelog yet as definition file:
https://github.com/mikepenz/AboutLibraries/tree/develop/library/src/main/res/values

**Comment by androideveloper** [comment]
Ok, ok, thanks :)

**Comment by mikepenz** [comment]
@androideveloper yes this is. Because auto scan just tries to detect libs which do not contain the library definition file within the library. 

My libs (and some others) contain the definition file within the lib, so they are faster detected.

You can exclude them. (I assume you do not directly use the `Android-Iconics` and the `FastAdapter` those two are dependencies of the `AboutLibraries` and the `MaterialDrawer` (just their core's so they do not add many methods)

**Comment by androideveloper** [comment]
@mikepenz Thanks! Though I haven't directly included `Android-Iconics`, but I use it besides use in `MaterialDrawer`, so I will not exclude it)) But have excluded `FastAdapter` and `materialize` ))

**Comment by mikepenz** [comment]
@androideveloper it's fine ;)
