### ISSUE TITLE
With gradle plugin enabled, unable to include external libs for e.g. c++ dependencies

### ISSUE THREAD

**Issue by mutagene** [mikepenz/AboutLibraries#471]
## About this issue

I have used the external libs to declare c++ dependencies. When I enabled the gradle plugin, this manually entered data is completely ignored. Checking AboutLibraries (Libs.kt:106), I see:
```
        // if we used the gradle plugin to resolve libraries, only use those
        if (foundPluginLibraryIdentifiers.isEmpty()) {
...
            //add external libs
            for (externalIdentifier in foundExternalLibraryIdentifiers) {
...
            }
        }
```

So clearly this is by design. However, given that the gradle plugin can never gather data on c++ libraries, it seems necessary that there be some mechanism for user added data.

## Details
- [x] Used library version: 8.0.0-b06

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/AboutLibraries/issues)
- [x] Checked out the [sample application](https://github.com/mikepenz/AboutLibraries/tree/develop/app)
- [x] Read the [README](https://github.com/mikepenz/AboutLibraries/blob/develop/README.md)
- [x] Checked out the [CHANGELOG](https://github.com/mikepenz/AboutLibraries/releases)
- [x] Read the [MIGRATION GUIDE](https://github.com/mikepenz/AboutLibraries/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment]
@mutagene thanks for the report. 

It depends. if the c++ dependency is provided as a *.so file bundled into a *.jar or *.aar and shipped via maven central it should work exactly the same as for other libs. 
You are right though if you manually copy paste (or it is an in-house) library that it won't be found right now. 

As of now there is basically still the "old" approach possible (at least it should) which allows you to provide the library information as a "definition file" in the project. E.g. https://github.com/mikepenz/FastAdapter/blob/develop/library-core/src/main/res/values/library_fastadapter_strings.xml 
And then (as the automatic detection is no longer active, due to prevent duplicates due to backwards compatibility) show it by enabling it via providing its id: https://github.com/mikepenz/AboutLibraries/blob/develop/library/src/main/java/com/mikepenz/aboutlibraries/LibsBuilder.kt#L103 
(if it is currently not possible this would be then an oversight on my end) 


I like the point of simplifying this further though, maybe offer the option to provide additional libraries (and perhaps also manual data to overwrite auto detected information) via a config folder. which will then be automatically used.

**Comment by mutagene** [comment]
I tried using `withLibraries`, but it seems that any libraries added this way area also excluded by the `foundPluginLibraryIdentifiers.isEmpty()` exclusion above, unless I am doing something wrong? It seems the only way I can get my definition files to be displayed is to prefix with `define_plu_` - but this does not seem correct. Maybe a harmless workaround, though?

**Comment by mikepenz** [comment]
I will have a look at this one. May have restricted it too much in that case :/ 

It is definitely harmless :) but shouldn't be necessary.

Will investigate. Thank you so much for the report

**Comment by mutagene** [comment]
Thanks. The `define_plu` works fine for me, in any case. Thanks for your work on the library.

**Comment by mikepenz** [comment]
Thank you so much. 

So I looked further into this, I believe we should make `define_plu` the new rule for adding custom libraries. as it will just tell the lib to just display it and trust the data. 

Will still be a bit of a task to ensure proper documentation everywhere :) 

Thanks again so much for the report!

**Comment by ViliusSutkus89** [comment]
I had the same problem. Have a library with 25 native dependencies that I build from source along the main library. Initially I stuffed my POM license URL entry with copyright texts from my dependencies. It works with play-services-oss-licenses, but alternative implementations ignore my workaround.

I cannot do `define_plu` or do other similar methods because most of them are done when building the client application, not my library.

Ended up creating a bunch of "licenseOnly" projects, just so I could gradle-depend on them in my library. Gradle-depend means that AboutLicenses, play-services-oss-licenses and all the other solutions will pick them up correctly.

https://github.com/ViliusSutkus89/licenseOnly
