### ISSUE TITLE
After building with R8 library stops returning licenses

### ISSUE THREAD

**Issue by ar-g** [mikepenz/AboutLibraries#484]
Release build doesn't return licenses, code for the library:

```kotlin
private val libs by lazy { Libs(context) }

    override suspend fun getLibraries(): List<Library> {
        return withContext(Dispatchers.IO) {
            libs.prepareLibraries(context, autoDetect = false)
                .asSequence()
                .filter { !(it.license?.licenseWebsite.isNullOrEmpty() && it.libraryWebsite.isEmpty()) }
                .distinctBy { it.libraryName }
                .map { it.toDomainEntity() }
                .toList()
        }
    }
```

Tried proguard rules:

```
-keep class .R
-keep class **.R$* {
    <fields>;
}
-keepclasseswithmembers class **.R$* {
    *;
}
```
Module structure:

```
/app-module
/features/license-module
```

The interesting part is that release apk contains all the strings and resources 🤔

**Comment by mikepenz** [comment]
Hmmm usually this is the case if the resources can not be retrieved. This may be due to a different package name, resources being stripped, ...

See here:
https://github.com/mikepenz/AboutLibraries#fragment


Try this:

```
.withFields(R.string::class.java.fields)
```

**Comment by mikepenz** [comment]
@ar-g have you had a chance to pass the fields? did it solve your problem?

**Comment by ar-g** [comment]
```
.withFields(R.string::class.java.fields)
```

This code only gathers libraries from the specific package, in this case, we only receive AboutLibrary. We can't reference from `features/licenses` module `app` module. 

But proguard rules started working, perhaps configuration mistake, I'm trying to get minimal proguard rules currently.

**Comment by mikepenz** [comment]
so there are 2 things to the topic.

the aboutLibraries retrieves the strings from the R fields via their well known naming scheme. 
Strings because I believe generating a ton of classes, ... is not necessary and strings have the advantage of being theoretically translateable if wished. 

this whole thing tries to be kind of smart. 

So in most cases people can provide the string fields so we don't have to try to resolve it via reflection, but not in all cases that's possible. 

Especially if the package name got obfuscated, and the reflection is not able to resolve the proper class for the R fields. 

If your proguard config adjusts the package of the R class and you can't access the R field from the other module. you still can go the reflection approach by having this code modified for your use-case (e.g. specify the package, ....) 

and then pass in the fields :) 

https://github.com/mikepenz/AboutLibraries/blob/develop/library-core/src/main/java/com/mikepenz/aboutlibraries/util/GenericsUtil.kt#L18-L45

**Comment by mikepenz** [comment]
I hope this resolves your problem :)
