### ISSUE TITLE
Better select useful dependencies to list during plugin generation

### ISSUE THREAD

**Issue by AllanWang** [mikepenz/AboutLibraries#520]
Not exactly a bug report so I'm removing the template. Applies to v8.3.0. I have been on 7.x.x until today

Related issues: #510

We should be more selective when generating the plugin list instead of just displaying every single dependency.

Looking at the readme screenshot, we see listings like Activity, Arch-Common, etc. Those won't really be useful for others, and seems to dilute the list. I would bundle AppCompat there as well, but that may be debatable.

Multi module projects also seem to get multiple listings:

* Material dialogs doesn't seem to list properly despite being defined in about libraries. The title is the package name + module name, and there is now a new entry for each sub module.
* There is a dagger listing + dagger lint rules listing
* FastAdapter has 6 listings for me, and a lot of them don't even fit the screen so they are ellipsized and look the same.
* We have IntelliJ IDEA Annotations, JSR-250 Common Annotation, and a bunch of other annotations that are part of a separate dependency
* kotlin for me is showing kotlin-stdlib, kotlin-stdlib-common, kotlin-stdlib-jdk7, kotlinstd-lib-jdk8, which is probably inevitable due to other library dependencies.

We're not going to be able to solve all these problems without some manual work, but I think some things like multi module dependencies and core android dependencies can be addressed. The other alternative would be for us to list the dependencies ourselves to make the list more meaningful, but at that point the plugin doesn't seem to be needed.

**Comment by mikepenz** [comment]
@AllanWang I understand the request and see the ideas behind it. 

Generally speaking I prefer and I believe that every single library and it's license should be included for the complete attribution of your project. if a lib is not included in the attribution the lib may should be removed from the project alltogether


That being said. I believe that you are not the only one who'd love to have a merging possibility to combine libs into single listings. which makes kind of sense in some ways. 

I am / was thinking of some clever merging logic which will check crucial parts of the libs like the group or the start of the name or other indicators to merge together the libs. 

But most of the approaches will kind of fail again.

- Not all split apart libs use the same group to start with, many use the group wider than a single lib, ... 
- Names are also not consistent in any way. 

So the only way I see is to allow some kind of configuration in a way like:

- regex match for title, regex match for group, regex match for libraryId
- definition which one will be the `main` e.g. it's attributes will be used (name, ...)

**Comment by AllanWang** [comment]
How are you resolving the URLs for each dependency? That might be a good place to start, given that dependencies with the same license and URL (and maybe description) don't really offer any more attribution

**Comment by AllanWang** [comment]
I also see entries (like Material Dialogs) that don't have a license nor an associated URL. Does it still make sense to list it at that point? Perhaps that would need some kind of lookup where it trims off sections of the dependency until we have a useful entry

**Comment by mikepenz** [comment]
Oh url may be a good idea, I still guess though it will fail badly possibly for jetpack libs. 
Not sure how the merge strategy would look like there. But that's a good idea to try

-----

```
I also see entries (like Material Dialogs) that don't have a license nor an associated URL. Does it still make sense to list it at that point? Perhaps that would need some kind of lookup where it trims off sections of the dependency until we have a useful entry
``` 
there's actually the gradle task which lists libraries with missing information, so you can easily then add the information to one of the config lists. 

Possibly even to the libraries included overwrite mechanism if a lib is unlikely to add missing details: https://github.com/mikepenz/AboutLibraries/blob/develop/library-definitions/src/main/res/raw/custom_license_mappings.prop

Personally I think those should be included, better link to the project (because they will in 99% of cases have a license) than dropping it, and probably running into trouble for not giving credits.

**Comment by AllanWang** [comment]
With regards to figuring out which dependencies are referenced, I'm not sure if it should be using every dependency in the project. Libraries are supposed to provide licenses that respect their own dependency, so referencing the immediate dependencies should suffice. Libraries should use `implementation` anyways, so direct usage to an inherited library needs to be declared.

This probably won't be a big issue if we can better trim the list, but I'm coming from the idea of one user who uses a big library, and ending up with a long list of entries. It'll make it harder for others to know which library they actually included, but I don't know what's more important.

**Comment by AllanWang** [comment]
Another interesting thing:

https://github.com/AllanWang/KAU/search?q=%22dependencies.fastadapter%22&unscoped_q=%22dependencies.fastadapter%22

My project only uses FastAdapter's `utils` and `diff` extensions, yet the entries list `diff`, `drag`, `expandable`, `swipe`, and `utils`.

This is probably something I need to investigate since I don't think any of my dependencies should be using the extra extensions anyways, but otherwise it's providing sources for calls within the library rather than within my app.

**Comment by mikepenz** [comment]
The plan to support those cases of not going to the transitive dependencies sounds good, but would make the default the current behavior and allow an option to change the behavior. First we'd have to see first if we get the "level" of a dependency though.  

From a "giving credits" side, generally it would be beneficial to include the whole tree though, as none would function without it's sub dependencies which most likely is written by somebody else. so the creator of the sub dependency shall get credits too. and based on the libs I used almost never have I seen the license to include sub dependencies, as those deps are automatically transitively pulled. 


----

Oh that one is actually due to the `utils` module which also offers utils for expandable and drag. you could disable transitive dependencies for the utils one to stop it to include others

**Comment by mikepenz** [comment]
v10.x.y is now in the works. I'd love to collect some early feedback on it, and potentially see which options we either have in the plugin to cover such situations. 

But ultimately v10 has a larger focus on compose whereas the raw `libraries` are passed, as such any filtering / mapping / ... as needed can be done :) 

Closing this one, please report any suggestions in the v10 PR :) 

Thank you very much
