### ISSUE TITLE
Autodetect library versions

### ISSUE THREAD

**Issue by johnjohndoe** [mikepenz/AboutLibraries#55]
Please correct me if I am wrong but I think with the current implementation all library version are hard-coded in either the supplied library XML or the library XML which people generated and manually added to their application projects.

I would love to see that the library version is parsed from `build.gradle` so no-one has to maintain this any longer. I like to mention [Gradle-License-Report](https://github.com/RobertFischer/Gradle-License-Report) by @RobertFischer who pursues a similar thing for license information.

**Comment by mikepenz** [comment]
@johnjohndoe yeah you are right, right now i had no idea how to get the real version number during runtime. once i thought it would be great to get it from the AndroidManifest, but all my tries failed. 

I've seen this repository (i saw that you contributed to it so i stared it) and it's really interesting. And you are right it would be great if those versions are fetched either from the build.gradle or from the pom.xml. 
@RobertFischer has a different approach to generate a report (as far as i've seen) and you can use this information. 
I hope i can somehow combine the idea behind AboutLibraries and add the version functionality (or even the general definition file generation (who knows :D)) from a gradle plugin.

**Comment by johnjohndoe** [comment]
I would highly suggest that you parse the version numbers from `build.gradle` at **compile time** instead of run time. Nobody wants to slow down her app when this can be handled beforehand.

Another project which deals with evaluating dependencies is [Gradle View](http://plugins.jetbrains.com/plugin/7150). Please have a look.

**Comment by mikepenz** [comment]
@johnjohndoe yeah you are right, this would be the best solution. I'll take a look at it in the next few days. Would be awesome if i can get it working this way. 

Thanks

**Comment by tprochazka** [comment]
This plugin
https://github.com/ben-manes/gradle-versions-plugin
is able to detect latest version of all dependencies directly from the maven repos.

So the same mechanism can be used to detect libraries version.

But. I don't understand why this library should do this. I think that version of the library is irrelevant.
Name if the lib, author, web, licence name and url to licence is enough I think ;-)
I see also future problem that you are using strings.xml for the configuration, because string.xml is not compressed inside of APK because of fast access, so the library will be relative huge in the future.

**Comment by johnjohndoe** [comment]
Any progress on this?

**Comment by mikepenz** [comment]
@johnjohndoe not yet

**Comment by RobertFischer** [comment]
Hey there. I'm the author for Gradle Versions plugin. I wrote it because we needed that information for legal at $BIGCORP. Pretty much everything you need is in the pom file, assuming it's well-written. If it's not, a quick look inside jars for various well-known license file is easy to do. Theoretically, you could check for the license files at runtime, and parse out what you can from the jar file's manifest file, but the pom file approach just seemed a lot simpler.

**Comment by manjunathc23** [comment]
+1

**Comment by mikepenz** [comment]
I am open for an **PR** for this. I will close this now as it is not planned from my side.

**Comment by johnjohndoe** [comment]
@mikepenz Did you implement auto detection meanwhile? I ask because the [ProGuard section](https://github.com/mikepenz/AboutLibraries#proguard) of your README.md mentions "...  enable the libraries auto detection".

**Comment by mikepenz** [comment]
I started looking into doing it during compile time based on the dependency, but I could not resolve the problem with transitive dependencies.. https://discuss.gradle.org/t/resolve-transitive-dependencies/30534
