### ISSUE TITLE
Possible enhancement: Increase touch-target size

### ISSUE THREAD

**Issue by iainism** [mikepenz/AboutLibraries#571]
I have recently submitted an app that uses AboutLibraries via the Google Play console.  The pre-launch report has flagged some (minor) accessibility issues, e.g. in relation to touch-target size for the link to library sources.  As an enhancement, would it be possible to have an (optional?) item layout available that provides the minimum recommended touch-target size of 48dp by 48dp?  (I think this could be done by simply changing which part of the item layout is clickable to fire the intent to go to the library's homepage)

Snapshot of report: [https://imgur.com/a/sj0bcQB](https://imgur.com/a/sj0bcQB)

**Comment by mikepenz** [comment]
@iainism if you'd love to adjust layouts used by the UI you can thanks to the flexible android build system overwrite them :) 

Copy paste this to your project:
https://github.com/mikepenz/AboutLibraries/blob/develop/library/src/main/res/layout/listitem_opensource.xml

and modify the sizes you would love to be different.

**Comment by mikepenz** [comment]
I hope you were able to resolve the issue with the provided information

**Comment by iainism** [comment]
Yes - sorry for the delay following up!

**Comment by JulianJB** [comment]
Hi @mikepenz, I came across this thread because I wanted to fix the same accessibility issues reported by the auto-generated pre-launch report on Google Play Console, so I tried your solution, and indeed it does work but wouldn't this be a manual "hard-coded" fix? What I mean is if you change some properties of the XML files in future updates of the library, would I need to re-apply the previous changes to the new files to get the new enhancements, otherwise the Android build system will just ignore your changes and keep using the old files imported into my project?

**Comment by mikepenz** [comment]
@JulianJB currently there are no significant changes planned to the UI. That may change if we start to provide a compose based UI. 

So you should be rather safe updating the xml files. also we wouldn't change this on surprise.
