### ISSUE TITLE
GPL license 

### ISSUE THREAD

**Issue by mbiebl** [mikepenz/AboutLibraries#893]
Version: 10.7.0

Related to #892, I also wanted to add a custom library (which is included as git submodule), that uses GPL-3-0-or-later.
What I did is basically the same as in
https://github.com/mbiebl/AboutLibraries/commit/964ba8830e66e5954a9b83b7a9f7838f00ce93da

Yet, the license information is not shown as can be seen in the AboutLibraries demo app.

**Comment by mbiebl** [comment]
![image](https://github.com/mikepenz/AboutLibraries/assets/3609611/7cf7a5cd-b044-4850-acc9-5a3e79b10dac)

**Comment by mikepenz** [comment]
The `id` for this license is `GPL-3.0-or-later` (`3.0` instead of `3-0`)
- https://github.com/mikepenz/AboutLibraries/blob/develop/plugin-build/plugin/src/main/kotlin/com/mikepenz/aboutlibraries/plugin/mapping/SpdxLicense.kt#L179

<img width="199" alt="Screenshot 2023-06-19 at 20 46 40" src="https://github.com/mikepenz/AboutLibraries/assets/1476232/cc456201-8ba0-4822-aac3-90f229b03cf1">

**Comment by mbiebl** [comment]
Argh, sorry for mixing this up (3.0 vs 3-0). Not sure how this happened. Thanks for having a closer look.

I can confirm now, that this work in the main Activity. 
In the "Compose Activity" though, tapping on the license info does *not* open a browser with a link to spdx.org. 
Can you confirm this behaviour?

**Comment by mikepenz** [comment]
Yes that is correct. In the `Compose` default behaviour it would show a dialog instead of launching a web viewer. 

However for this license the plugin fails to fetch the respective text format license. Normally the SPDX website exposed a `*.txt` file per html page: https://spdx.org/licenses/GPL-3.0-or-later.html -> https://spdx.org/licenses/GPL-3.0-or-later.txt however that one is not accessible for this license. 

So this information is not available.

You can connect a `onLibraryClick` and launch the web viewer on the `url` though. 


```
val uriHandler = LocalUriHandler.current
uriHandler.openUri(uri)
```

**Comment by mbiebl** [comment]
Is it possible to change the default behaviour of the Compose UI module to behave like the old/legacy UI module?

If not, there is probably nothing left to do in this ticket and it can be closed.

**Comment by mikepenz** [comment]
You mean it launching the browser with the license?

You can, pass in the `onLibraryClick` function and make it launch the url.
